Electo.Web/Areas/Admin/Controllers/BrandsController.cs
using AutoMapper;
using Electo.DAL.Context;
using Electo.DAL.Entities;
using Electo.PL.Models;
using Electo.PL.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Electo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admins")]
    public class BrandsController : Controller
    {
        private readonly IMapper _mapper;

        private readonly ApplicationDbContext _context;
        private UnitOfWork _unitOfWork;
        public BrandsController(IMapper mapper, ApplicationDbContext context)
        {
            _context = context;
            _unitOfWork = new UnitOfWork(_context);
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var getAllBrands = _unitOfWork.BrandRepository.Get();
            return View(_mapper.Map<IEnumerable<BrandVM>>(getAllBrands));

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(BrandVM  brand)
        {
            if (ModelState.IsValid)
            {
                var MappBrand = _mapper.Map<Brand>(brand);
                _unitOfWork.BrandRepository.Add(MappBrand);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(brand);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var brand = _unitOfWork.BrandRepository.GetById(id);
            if (brand == null)
            {
                return NotFound();
            }
            var brandModel = _mapper.Map<BrandVM>(brand);
            return View(brandModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(BrandVM brand)
        {
            if (ModelState.IsValid)
            {
                var MappBrand = _mapper.Map<Brand>(brand);
                _unitOfWork.BrandRepository.Edit(MappBrand);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(brand);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var brand = _unitOfWork.BrandRepository.GetById(id);
            if (brand == null)
            {
                return NotFound();
            }
            var brandModel = _mapper.Map<BrandVM>(brand);
            return View(brandModel);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id , BrandVM vM )
        {
            _mapper.Map<Brand>(vM);
            _unitOfWork.BrandRepository.GetById(id);
            _unitOfWork.BrandRepository.Delete(id );
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Electo.Web/Areas/Admin/Views/Brands/Create.cshtml
@model Electo.PL.Models.BrandVM
@{
    ViewBag.Title = "Add Brand";
}

<h1>Add Brand</h1>
<br>
<br>
<form asp-controller="Brands" asp-action="Create" method="post">

    <label>Brand Name</label>
    <input type="text" asp-for="BrandName" class= "form-control"/>
    <span class="text-danger" asp-validation-for="BrandName"></span>
    <br>
    <center>
     <input type="submit" value="Save" class="btn btn-primary"/>
    </center>
</form>

Electo.Web/Areas/Admin/Views/Brands/Delete.cshtml
@model Electo.PL.Models.BrandVM
@{
    ViewBag.Title = "Delete Brand";
}

<h1>Delete Brand </h1>
<br>
<br>
<form  asp-controller="Brands" asp-action="Delete" method="post" 
 class = "form-group">

    <label asp-for="BrandName"> Brand Name</label>
    <input type="text" asp-for="BrandName" disabled class= "form-control"/>
    <br>
    <center>
     <input type="submit" value="Delete" class="btn btn-danger"/>
    </center> 
</form>

Electo.Web/Areas/Admin/Views/Brands/Edit.cshtml
@model Electo.PL.Models.BrandVM
@{
    ViewBag.Title = "Edit";
}
<h1>Edit Brand</h1>
<br>
<br>
<form  asp-controller="Brands" asp-action="Edit"
  method="post">

    <label asp-for="BrandName"> Brand Name </label>
    <input type="text" asp-for="BrandName"  class= "form-control"/>
    <span class="text-danger" asp-validation-for="BrandName"></span>
    <br>
    <center>
     <input type="submit" value="Save" class="btn btn-primary"/>
    </center> 
</form>

<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

Electo.Web/Areas/Admin/Views/Brands/Index.cshtml
@model IEnumerable<Electo.PL.Models.BrandVM>


@{
     ViewBag.Title = "Brands";

}

<br>
<br>
<h1 style="text-align:center">All Brands</h1>
<br>
    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                    <a asp-controller="Brands" asp-action="Create" 
                    class="btn btn-primary"style="margin-bottom:5px">
                    Add Brand </a>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped text-center table-hover js-basic-example dataTable">
                                <thead>
                                 <tr>
                                  <th class= "text-center"> Brand Name </th>
                                  <th class= "text-center"> Edit </th>
                                  <th class= "text-center"> Delete </th>
                               </tr>
                               </thead>

                               <tbody>
                              @foreach (var item in Model){
                                    <tr>
                                      <td class= "text-center">@item.BrandName</td>
                                      <td><a asp-controller="Brands" asp-action="Edit"
                                          asp-route-id="@item.Id" class="btn btn-primary">Edit</a></td>
                                      <td><a asp-controller="Brands"asp-action="Delete"
                                          asp-route-id="@item.Id" class="btn btn-primary">Delete</a></td>
                                    </tr>
                                }

                               </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
   @section DataTableSectionDepartment{
    <script>
        $(function () {
            $('.js-basic-example').DataTable({
                responsive: true,
                paging: true,
                pageLength: 3,
                bSort: true,
                bFilter: true,
                //bLengthChange: false,
                //bInfo: false,
                lengthMenu: [[3, 5, 10, 25, 50, -1], [3, 5, 10, 25, 50, "All"]],

            });
        });
    </script>
}