Electo.Web/Areas/Admin/Controllers/CategorysController.cs
using AutoMapper;
using Electo.DAL.Context;
using Electo.DAL.Entities;
using Electo.PL.Models;
using Electo.PL.Repositories;
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;

namespace Electo.Web.Areas.Admin.Controllers
{
    [Area("Admin")]
    [Authorize(Roles = "Admins")]
    public class CategorysController : Controller
    {
        private readonly IMapper _mapper;

        private readonly ApplicationDbContext _context;
        private UnitOfWork _unitOfWork;
        public CategorysController(IMapper mapper , ApplicationDbContext context)
        {
            _context = context;
            _unitOfWork = new UnitOfWork(_context);
            _mapper = mapper;
        }
        public IActionResult Index()
        {
            var getAllCategory = _unitOfWork.CategoryRepository.Get();
            return View(_mapper.Map<IEnumerable<CategoryVM>>(getAllCategory));

        }
        public IActionResult Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Create(CategoryVM category)
        {
            if (ModelState.IsValid) 
            {
                var MappCategory = _mapper.Map<Category>(category);
                _unitOfWork.CategoryRepository.Add(MappCategory);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(category);
        }

        public IActionResult Edit(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var category = _unitOfWork.CategoryRepository.GetById(id);
            if (category == null)
            {
                return NotFound();
            }
            var categoryModel = _mapper.Map<CategoryVM>(category);
            return View(categoryModel);
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Edit(CategoryVM category)
        {
            if (ModelState.IsValid) 
            {
                var MappCategory = _mapper.Map<Category>(category);
                _unitOfWork.CategoryRepository.Edit(MappCategory);
                _unitOfWork.Save();
                return RedirectToAction("Index");
            }
            return View(category);

        }

        public IActionResult Delete(int? id)
        {
            if (id == null)
            {
                return BadRequest();
            }
            var category = _unitOfWork.CategoryRepository.GetById(id);
            if (category == null)
            {
                return NotFound();
            }
            var categoryModel = _mapper.Map<CategoryVM>(category);
            return View(categoryModel);

        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public IActionResult Delete(int id ,CategoryVM vM )
        {
            _mapper.Map<Category>(vM);
            _unitOfWork.CategoryRepository.GetById(id);
            _unitOfWork.CategoryRepository.Delete(id);
            _unitOfWork.Save();
            return RedirectToAction("Index");
        }
    }
}

Electo.Web/Areas/Admin/Views/Categorys/Create.cshtml
@model Electo.PL.Models.CategoryVM
@{
    ViewBag.Title = "Add Category";
}

<h1>Add Category</h1>
<br>
<br>
<form asp-controller="Categorys" asp-action="Create" method="post">

    <label>Category Name</label>
    <input type="text" asp-for="CategoryName" class= "form-control"/>
    <span class="text-danger" asp-validation-for="CategoryName"></span>
    <br>
    <center>
     <input type="submit" value="Save" class="btn btn-primary"/>
    </center>
</form>

Electo.Web/Areas/Admin/Views/Categorys/Delete.cshtml
@model Electo.PL.Models.CategoryVM
@{
    ViewBag.Title = "Delete";
}

<h1>Delete Category</h1>
<br>
<br>
<form  asp-controller="Categorys" asp-action="Delete" method="post" 
 class = "form-group">

    <label asp-for="CategoryName"> Category Name </label>
    <input type="text" asp-for="CategoryName" disabled class= "form-control"/>
    <br>
    <center>
     <input type="submit" value="Delete" class="btn btn-danger"/>
    </center> 
</form>

Electo.Web/Areas/Admin/Views/Categorys/Edit.cshtml
@model Electo.PL.Models.CategoryVM
@{
    ViewBag.Title = "Edit";
}
<h1>Edit Department</h1>
<br>
<br>
<form  asp-controller="Categorys" asp-action="Edit"
  method="post">

    <label asp-for="CategoryName"> Category Name </label>
    <input type="text" asp-for="CategoryName"  class= "form-control"/>
    <span class="text-danger" asp-validation-for="CategoryName"></span>
    <br>
    <center>
     <input type="submit" value="Save" class="btn btn-primary"/>
    </center> 
</form>

<script src="~/jquery/jquery.min.js"></script>
<script src="~/jquery-validate/jquery.validate.min.js"></script>
<script src="~/jquery-validation-unobtrusive/dist/jquery.validate.unobtrusive.min.js"></script>

Electo.Web/Areas/Admin/Views/Categorys/Index.cshtml
@model IEnumerable<Electo.PL.Models.CategoryVM>
@*@using FWshop.Resource.Department
@using Microsoft.Extensions.Localization
@inject IStringLocalizer<Resource> Resource*@

@{
     ViewBag.Title = "Categorys";
     //var Culture = System.Threading.Thread.CurrentThread.CurrentCulture.Name;

}

@*@if(Culture=="en-US"){
    <h3 style="text-align:right">
    <a asp-controller="Department" asp-action="Index" asp-route-culture="ar-EG">
    @Resource["Arabic"]</a>
    </h3>
}
@if(Culture=="ar-EG"){
   <h3 style="text-align:left">
   <a asp-controller="Department" asp-action="Index" asp-route-culture="en-US">
    @Resource["English"]</a>
   </h3>
}
<br>*@

<h1 style="text-align:center">All Categorys</h1>
<br>
<br>
@*<table class ="table table-striped table-bordered text-center">
    <tr>
          <th class= "text-center"> @Resource["DepaName"]</th>
          <th class= "text-center"> @Resource["DepCode"]</th>
          <th class= "text-center"> @Resource["Edit"] </th>
          <th class= "text-center"> @Resource["Delete"]</th>
    </tr>
    @foreach (var item in Model){
        <tr>
          <td class= "text-center">@item.DepartmentName</td>
          <td class= "text-center">@item.DepartmentCode</td>
          <td><a asp-controller="Department"asp-action="Edit"
              asp-route-id="@item.Id" class="btn btn-primary">@Resource["Edit"]</a></td>
          <td><a asp-controller="Department"asp-action="Delete"
              asp-route-id="@item.Id" class="btn btn-primary">@Resource["Delete"]</a></td>

        </tr>
    }
</table>*@

    <div class="container-fluid">
        <div class="row clearfix">
            <div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">
                <div class="card">
                    <div class="header">
                    <a asp-controller="Categorys" asp-action="Create" 
                    class="btn btn-primary"style="margin-bottom:5px">
                    Add Category  </a>
                    </div>
                    <div class="body">
                        <div class="table-responsive">
                            <table class="table table-bordered table-striped text-center table-hover js-basic-example dataTable">
                                <thead>
                                 <tr>
                                  <th class= "text-center"> Category Name </th>
                                  <th class= "text-center"> Edit </th>
                                  <th class= "text-center"> Delete </th>
                               </tr>
                               </thead>

                               <tbody>
                              @foreach (var item in Model){
                                    <tr>
                                      <td class= "text-center">@item.CategoryName</td>
                                      <td><a asp-controller="Categorys" asp-action="Edit"
                                          asp-route-id="@item.Id" class="btn btn-primary">Edit</a></td>
                                      <td><a asp-controller="Categorys"asp-action="Delete"
                                          asp-route-id="@item.Id" class="btn btn-primary">Delete</a></td>
                                    </tr>
                                }

                               </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
   
   @section DataTableSectionDepartment{
    <script>
        $(function () {
            $('.js-basic-example').DataTable({
                responsive: true,
                paging: true,
                pageLength: 3,
                bSort: true,
                bFilter: true,
                //bLengthChange: false,
                //bInfo: false,
                lengthMenu: [[3, 5, 10, 25, 50, -1], [3, 5, 10, 25, 50, "All"]],

            });
        });
    </script>
}